### ISSUE TITLE
Window selector popup appears on wrong screen

### ISSUE THREAD

**Issue by chrisirwin** [Leleat/Tiling-Assist#25] opened 2021-01-25 16:47 UTC
When snapping a window to a half (whether left/right or top/bottom), this extension pops up a selector to chose another window to snap in the other half.

The grouped program selector appears in the correct location, but the individual window expansion always appears on the left monitor.

**Comment by Leleat** [comment] 2021-01-25 16:53
Which version/commit of the extension are you using (from EGO or from github)?

**Comment by chrisirwin** [comment] 2021-01-25 16:55
The one published on extensions.gnome.org

**Comment by Leleat** [comment] 2021-01-25 17:00
For may understanding for example:

You have monitor 1 (on the left) and monitor 2 (on the right). If you tile a window to the right half on monitor 2, the dash (popup selector) appears on monitor 2 in the left screen half. But if you activate a window, it will be tiled to monitor 1? Did I get it right?

**Comment by chrisirwin** [comment] 2021-01-25 17:14
Not exactly. This bug is just about the "dash" popup specifically:

1. Tile monitor to right half of monitor 2
2. Dash appears on left half of monitor 2
3. However, there are multiple firefox windows, so when you hover over firefox it pops up a window selector to pick a specific window. This appears on the right half of monitor 1 (wrong half and wrong monitor)


This doesn't seem to have any effect on where the window is maximized, although that is sometimes broken as well, though I haven't figured out exactly how. sometimes it works, sometimes it doesn't. Sometimes windows snap to where you expect only to immediately be unsnapped back to where they came from. Ultimately, it also isn't a feature I desire, so I haven't spent a lot of time narrowing it down.

**Comment by Leleat** [comment] 2021-01-25 17:33
>     Tile monitor to right half of monitor 2
>     Dash appears on left half of monitor 2
>     However, there are multiple firefox windows, so when you hover over firefox it pops up a window selector to pick a specific window. This appears on the right half of monitor 1 (wrong half and wrong monitor)

I just tried out the EGO version. Tried with Monitor 1 as my main monitor and then with monitor 2 but I can't reproduce it. For me the window preview always appears correctly under the app dash. Can you try the master branch and see if the problem persists?

Also please tell me your:
- Distro (incl. version)
- GNOME version
- X11 or Wayland

**Comment by chrisirwin** [comment] 2021-01-25 18:20
* Fedora 33
* Gnome 3.38
* Wayland

Tried master branch, but it didn't work:

$ cd tmp
$ git clone https://github.com/Leleat/Tiling-Assist.git
$ cp -a Tiling-Assist/tiling-assistant\@leleat-on-github/ ~/.local/share/gnome-shell/extensions/
$ restorecon -r ~/.local/share/gnome-shell/extensions/

This is the error in the system journal:
```
Jan 25 13:13:08 t460 gnome-shell[5066]: JS ERROR: Error: GSettings key show-label not found in schema org.gnome.shell.extensions.tiling-assistant
                                                           _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:580:23
                                                           createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:532:30
                                                           open@/home/cirwin/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js:1218:119
                                                           openDash@/home/cirwin/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js:583:10
                                                           tileWindow/sID<@/home/cirwin/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js:256:11

```
This is the on-screen error if I try to display the settings:

```
Error: Expected type string for argument 'property' but got type undefined

Stack trace:
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:533:46
  _init/<@/home/cirwin/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:41:20
  _init@/home/cirwin/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:39:37
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
  buildPrefsWidget@/home/cirwin/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:8:15
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
  
Reverting back to the EGO version works.

**Comment by Leleat** [comment] 2021-01-25 18:44
Wayland did cause some unexpexted trouble in the past (which didn't appear when using X11). I'll test it on Wayland as well once I get a chance.

> $ cp -a Tiling-Assist/tiling-assistant@leleat-on-github/ ~/.local/share/gnome-shell/extensions/
> $ restorecon -r ~/.local/share/gnome-shell/extensions/

I am not used to working in the terminal (not sure what the -a argument for `cp` or what `restorecon` does), if I don't have to.

> GSettings key show-label not found

I removed that option from the settings already. So I guess there was some problem when copying the files to the extensions folder. So just delete the original `tiling-assistant@leleat-on-github` folder completely and move the new one in. That should work.

**Comment by Leleat** [comment] 2021-01-26 15:23
I could reproduce it now. Issue should be fixed in master.

**Closed by Leleat** 2021-01-26 15:23 UTC
Labels: bug
