### ISSUE TITLE
Smaller middle gap.

### ISSUE THREAD

**Issue by DiCaius** [Leleat/Tiling-Assist#56] opened 2021-03-29 14:23 UTC
I was wondering if it would be possible to decrease the innermost x-gap by half for each window so the middle gap matches the others.

![Screenshot from 2021-03-29 11-20-32](https://user-images.githubusercontent.com/15234862/112851169-1a382480-9081-11eb-8bee-db0acd63bc70.png)

As you can see the middle gap kinda sticks out right now.

**Comment by Leleat** [comment] 2021-03-29 15:14
Currently each window has the gap applied around all edges. So you'll get a double gap whenever windows are edge to edge. I plan to change the gaps to be uniform (although I don't plan to add inner and outer gaps like in tiling window managers) for everything.

One thing I am curious about... are you are using material shell? They already provide tiling functionality, don't they? I imagine this might lead to a conflict with my extension...

**Comment by DiCaius** [comment] 2021-03-29 15:36
That's nice to know, I'll look forward to this feature. I'm using material-shell indeed, there's no conflict as far I know, I'm currently using your plugin to simulate a better version of edge-tiling in their float layout (this layout doesn't have any tiling features). I haven't tried it all that much in different layouts with tiling capabilities but so far I haven't ran into any issues. They work really well together.

**Comment by Leleat** [comment] 2021-03-29 21:17
![scr](https://user-images.githubusercontent.com/53054301/112900960-aecb7280-90d3-11eb-884f-1bba96ae294d.png)

It landed in `master` now. It will however take a few weeks until it lands on EGO since I am currently refactoring code and still testing, if I introduced any regressions. Gnome 40 is also borked in `master` atm.

**Closed by Leleat** 2021-03-29 21:17 UTC
